version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 512M

  server-multi:
    build: .
    image: ton-bridge-rs:latest
    environment:
      - APP_REDIS_URL=redis://redis:6379
      - APP_SERVER_ADDRESS=0.0.0.0:3000
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 512M
