redis_url: "redis://127.0.0.1:6379"
redis_conn_timeout_sec: 5

server_address: "127.0.0.1:3000"

sse_heartbeat_interval_sec: 5

inbox_max_message_ttl_sec: 500
inbox_min_message_ttl_sec: 5
inbox_max_messages_per_client: 1000
inbox_inactive_ttl_sec: 600
