redis_url: "redis://127.0.0.1:6379"
redis_conn_timeout_sec: 5

server_address: "127.0.0.1:3000"
metrics_server_address: "127.0.0.1:3001"

sse_heartbeat_interval_sec: 5
sse_client_without_messages_ttl_sec: 120

inbox_max_message_ttl_sec: 500
inbox_min_message_ttl_sec: 5
inbox_max_messages_per_client: 1000
inbox_inactive_ttl_sec: 600

max_client_ids_per_connection: 100

global_stream_max_size: 30000
