version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 2s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 4G

  server:
    image: ton-bridge-rs:latest
    environment:
      - APP_REDIS_URL=redis://redis:6379
      - APP_SERVER_ADDRESS=0.0.0.0:3000
      - APP_LOG_LEVEL=info
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:3000/health" ]
      interval: 5s
      timeout: 2s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 256M
